name: flutter_onboarding
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  animated_bottom_navigation_bar: ^1.1.0
  flutter_icons: ^1.1.0
  page_transition: ^2.0.9
  get: ^4.6.5
  shared_preferences: ^2.0.15
  flutter_otp_text_field: ^1.1.1
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  firebase_storage: ^11.0.6
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.1.3
  file_picker: ^5.2.3
  google_sign_in: ^5.4.2
  share: ^2.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/